name: machine_learning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
    #- ipykernel
    #- ipympl=0.5.6
    #- jupyter
  - jupyterlab=2.1.5
    #- jupyter_contrib_nbextensions
  - matplotlib=3.1.1
  - numpy=1.18.5
  - scipy=1.4.1
  - pandas=1.0.5
  - nbconvert=5.6.1
  - nbstripout=0.3.9
    #- ipyvolume=0.6.0
    #- ipywidgets=7.5.1
  - h5py=2.10.0
  - seaborn=0.10.1
  - scikit-learn=0.23.1
  - click=7.1.2
  - pip
  - pip:
    - pyyaml==5.3.1
    - tensorflow==2.2.0
    - Keras==2.4.3
