#!/bin/sh

pip install tensorflow==2.2.0
pip install Keras==2.4.3

#downloading cnn saved model, since it is too large to include in the github repo
python gdrive-dl.py 1_eK-fQBmGCPEW2uAC7-I_5G5oZoWmIsq cnn/logs/CNN_xy_freezeFalse_dropoutTrue_lr1e-05_decay0.0_samples-1_saved_model.h5

#nbstripout --install
